name: Deploy WordPress Code

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SG_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SG_PORT }} ${{ secrets.SG_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -vvv \
            -o BatchMode=yes \
            -o StrictHostKeyChecking=no \
            -p ${{ secrets.SG_PORT }} \
            -i ~/.ssh/id_ed25519 \
            ${{ secrets.SG_USERNAME }}@${{ secrets.SG_HOST }} \
            "echo SSH connection successful"

      - name: Deploy themes
        run: |
          rsync -az \
            -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=no -p ${{ secrets.SG_PORT }} -i ~/.ssh/id_ed25519" \
            ./themes/ \
            ${{ secrets.SG_USERNAME }}@${{ secrets.SG_HOST }}:${{ secrets.SG_THEMES_PATH }}

      - name: Deploy plugins
        run: |
          rsync -az \
            -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=no -p ${{ secrets.SG_PORT }} -i ~/.ssh/id_ed25519" \
            ./plugins/ \
            ${{ secrets.SG_USERNAME }}@${{ secrets.SG_HOST }}:${{ secrets.SG_PLUGINS_PATH }}